In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

TASK 1

a)Select all rows of data from the second column, representing block IDs; save the resulting array as block_ids. Print the first five block IDs from block_ids.

b) Select five consecutive block IDs from block_ids, starting with the tenth ID, and save as block_id_slice

In [2]:
# Creating the complete tree_census array
tree_census = np.array([
    [3, 501451, 24, 0],
    [4, 501451, 20, 0],
    [7, 501911, 3, 0],
    [11, 502321, 15, 0],
    [15, 502321, 18, 0],
    [21, 502211, 8, 0],
    [27, 502211, 9, 0],
    [32, 501461, 21, 0],
    [35, 501461, 16, 0],
    [39, 502221, 7, 0],
    [42, 502221, 5, 0],
    [50, 502101, 12, 0],
    [56, 502101, 14, 0],
    [62, 502101, 10, 0],
    [68, 501431, 19, 0],
    [75, 501431, 22, 0],
    [82, 501441, 13, 0],
    [89, 501441, 17, 0],
    [97, 502351, 23, 0],
    [105, 502351, 28, 0],
    [112, 502351, 26, 0],
    [121, 501911, 11, 0],
    [130, 501911, 7, 0],
    [139, 501911, 9, 0],
    [148, 501951, 8, 0],
    [157, 501951, 10, 0],
    [166, 501951, 12, 0],
    [175, 501461, 14, 0],
    [184, 501461, 20, 0],
    [194, 501231, 16, 0],
    [204, 501231, 19, 0],
    [215, 501231, 13, 0],
    [226, 501321, 11, 0],
    [237, 501321, 17, 0],
    [249, 501321, 18, 0],
    [261, 501411, 23, 0],
    [274, 501411, 15, 0],
    [287, 501411, 9, 0],
    [300, 501581, 10, 0],
    [313, 501581, 7, 0],
    [326, 501581, 12, 0],
    [340, 501581, 16, 0],
    [354, 501581, 14, 0],
    [368, 501151, 19, 0],
    [383, 501151, 21, 0],
    [398, 501151, 8, 0],
    [414, 501231, 6, 0],
    [430, 501231, 11, 0],
    [446, 501231, 13, 0],
    [462, 501231, 10, 0],
    [479, 501231, 22, 0],
    [496, 501221, 17, 0],
    [513, 501221, 13, 0],
    [530, 501221, 6, 0],
    [547, 501221, 5, 0],
    [564, 501221, 11, 0],
    [582, 501221, 15, 0],
    [600, 501221, 8, 0],
    [618, 501221, 10, 0],
    [636, 501221, 7, 0],
    [655, 501221, 9, 0],
    [674, 501221, 14, 0],
    [693, 501221, 12, 0],
    [712, 501221, 9, 0],
    [732, 501221, 7, 0],
    [752, 501221, 10, 0],
    [772, 501221, 6, 0],
    [792, 501221, 11, 0],
    [812, 501221, 13, 0],
    [832, 501221, 12, 0],
    [853, 501221, 8, 0],
    [874, 501221, 16, 0],
    [895, 501221, 9, 0],
    [917, 501221, 5, 0],
    [939, 501221, 6, 0],
    [961, 501221, 11, 0],
    [983, 501221, 15, 0],
    [1005, 501221, 7, 0],
    [1028, 501221, 12, 0],
    [1051, 501221, 16, 0],
    [1074, 501221, 8, 0],
    [1097, 501221, 5, 0],
    [1120, 501221, 10, 0],
    [1144, 501221, 13, 0],
    [1168, 501221, 14, 0],
    [1192, 501221, 9, 0],
    [1217, 501221, 7, 0],
    [1242, 501221, 11, 0],
    [1267, 501221, 15, 0],
    [1292, 501221, 12, 0],
    [1317, 501221, 9, 0],
    [1343, 501221, 6, 0],
    [1369, 501221, 8, 0],
    [1395, 501221, 10, 0],
    [1421, 501221, 5, 0],
    [1448, 501221, 7, 0],
    [1475, 501221, 11, 0],
    [1502, 501221, 13, 0],
    [1529, 501221, 14, 0],
    [1556, 501221, 12, 0],
    [1584, 501221, 9, 0],
    [1612, 501221, 6, 0],
    [1640, 501221, 10, 0],
    [1668, 501221, 8, 0],
    [1696, 501221, 15, 0],
    [1725, 501221, 7, 0],
    [1754, 501221, 5, 0],
    [1783, 501221, 11, 0],
    [1812, 501221, 13, 0],
    [1841, 501221, 9, 0],
    ])


In [3]:
block_ids = tree_census[0:111,1]

In [4]:
# Select all rows of block ID data from the second column
print(block_ids)
# Print the first five block_ids
print(block_ids[0:5])

[501451 501451 501911 502321 502321 502211 502211 501461 501461 502221
 502221 502101 502101 502101 501431 501431 501441 501441 502351 502351
 502351 501911 501911 501911 501951 501951 501951 501461 501461 501231
 501231 501231 501321 501321 501321 501411 501411 501411 501581 501581
 501581 501581 501581 501151 501151 501151 501231 501231 501231 501231
 501231 501221 501221 501221 501221 501221 501221 501221 501221 501221
 501221 501221 501221 501221 501221 501221 501221 501221 501221 501221
 501221 501221 501221 501221 501221 501221 501221 501221 501221 501221
 501221 501221 501221 501221 501221 501221 501221 501221 501221 501221
 501221 501221 501221 501221 501221 501221 501221 501221 501221 501221
 501221 501221 501221 501221 501221 501221 501221 501221 501221 501221]
[501451 501451 501911 502321 502321]


In [5]:
# Select the tenth block ID from block_ids
tenth_block_id = block_ids[10]
print(tenth_block_id)

502221


In [6]:
# Select five block IDs from block_ids starting with the tenth ID
block_id_slice = block_ids[10:15]
print(block_id_slice)

[502221 502101 502101 502101 501431]


2- PANDAS
Making df and Series
The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

In [7]:
fruits = pd.DataFrame({"Apples":31, "Banana":21}, index=[0])
fruits

Apples  Banana
0      31      21

In [8]:
fruit_sales = pd.DataFrame({"Apples":[35, 41], "Banana":[21,34]}, index=["2017 Sales","2018 Sales"])
fruit_sales

Apples  Banana
2017 Sales      35      21
2018 Sales      41      34

Task 3

Create a variable ingredients with a Series that looks like:

In [9]:
ingredients = pd.DataFrame({"qty":["Flour", "Milk", "Eggs", "Spam"], "ingr":["4 cup", "1 cup", "2 large", "1 can"]})
ingredients

qty     ingr
0  Flour    4 cup
1   Milk    1 cup
2   Eggs  2 large
3   Spam    1 can

Task 4  
Write a Pandas program to compare the elements of the two Pandas Series.

In [10]:
list1 = [2,4,6,8,10]
df1 = pd.DataFrame(list1)
df1

0
0   2
1   4
2   6
3   8
4  10

In [11]:
list2 = [1,3,5,7,10]
df2 = pd.DataFrame(list2)
df2

0
0   1
1   3
2   5
3   7
4  10

In [12]:
print(df1 == df2)
print(df1 < df2)
print(df1 > df2)

       0
0  False
1  False
2  False
3  False
4   True
       0
0  False
1  False
2  False
3  False
4  False
       0
0   True
1   True
2   True
3   True
4  False


Task 5  
Create a pandas series from each of the items below: a list, numpy and a dictionary

In [13]:
mylist = list("abcdefghijklmnopqrstuvwxyz")
mylist

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [14]:
myarr = np.arange(26)
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [15]:
mydict = dict(zip(mylist, myarr))
mydict

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [16]:
data2 = pd.DataFrame(mylist, myarr)
data2

0
0   a
1   b
2   c
3   d
4   e
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

Task 6  
Use pandas to import the Titanic data frame.  
Explore the DataFrame using methods like head(), tail(), info()  
Check the number of passengers in each passenger class using value_counts().  
Calculate descriptive statistics for numerical variables (e.g., age, fare) using describe().  

In [17]:
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [18]:
titanic.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [19]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [20]:
titanic["class"].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [21]:
titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200